import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ContextWrapper } from "@/contexts/wrapper.context";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";
import { Toaster } from "@/components/ui/sonner";
// import { Toaster } from "sonner";

import "./globals.css";
import "./template-styles.css";
import "swiper/css";
import "swiper/css/navigation";

// FontAwesome CDN for icons
const FontAwesomeCDN = () => (
  <>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
      crossOrigin="anonymous"
      referrerPolicy="no-referrer"
    />
  </>
);

const PoppinsFont = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Imovel API Norman Dev</title>
        <meta name="description" content="Real estate platform" />
        <FontAwesomeCDN />
      </head>
      <body className={`${PoppinsFont.variable}  antialiased`}>
        <Toaster position="top-right" duration={2000} richColors />
        <ContextWrapper>
          <Header />
          {children}
          <Footer />
        </ContextWrapper>
      </body>
    </html>
  );
}
